name: Run GPM download code 
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 1 11 * *'

jobs:
  runcode:
    runs-on: ubuntu-latest
    steps:
      - name: Run  
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER_S}}
          key: ${{secrets.SSH_KEY_S}}
          command_timeout: 60m
          script: |
              module use /g/data3/hh5/public/modules
              module load conda/analysis3

              cd /g/data/ia39/aus-ref-clim-data-nci/gpm/code
              yr=2023
              python gpm.py -y $yr -u paolap -r 1/100
