# Created by Sam Green CLEX/UNSW, contact: sam.green@unsw.edu.au
# Date created: 25-10-2023

# This action is to download 3hr V07 GPM data from gpm1.gesdisc.eosdis.nasa.gov.

# This downloads the full day's data from 2 days from the date the script is run.

name: Run GPM download code 
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'

jobs:
  runcode:
    runs-on: ubuntu-latest
    steps:
      - name: Run  
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{secrets.PASSPHRASE}}
          command_timeout: 60m
          script: |
              #yr=$(date +'%Y')
              yr=2023
              cd /g/data/ia39/aus-ref-clim-data-nci/gpm/code
              bash gpm.sh yr
